### ISSUE TITLE
能否帮同步一个镜像

### ISSUE THREAD

**Issue by mrtylerzhou** [zhangguanzhang/gcr.io#2]
https://github.com/tektoncd/pipeline/releases
这个页面的`release.yaml`使用到了`tekton-releases`空间下的镜像,按照你这个方法查询里面没有,能否帮同步一份呢

**Comment by zhangguanzhang** [comment]
具体是哪个镜像，随便给个名字，例如`gcr.io/cloud-builders/git`

**Comment by mrtylerzhou** [comment]
谢谢.这个镜像在yaml里定义是这样的`gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller@sha256:e9128c33f5ee55c9d7fcafc914487a23dd0348e45bf14e644d71f8b73dae9061`,但是好像没用`tekton-releases`这个名称空间

**Comment by zhangguanzhang** [comment]
已经在同步了
https://github.com/zhangguanzhang/gcr.io/blob/develop/sync_list/google.loop

**Comment by mrtylerzhou** [comment]
谢谢大佬,真的是太感激了.刚刚接触不久,被这些问题搞的焦头烂额~~

**Comment by zhangguanzhang** [comment]
不对，它这个有层级
你把所有的gcr.io改成gcr.azk8s.cn就行了

**Comment by mrtylerzhou** [comment]
好的,晚会我试一下,thanks so much

**Comment by mrtylerzhou** [comment]
谢谢馆长,已经成功运行起来了
